[package]
name = "ou-bot-oxide"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive", "env"] }
color-eyre = "0.6.3"
dotenv = "0.15.0"
roux = "2.2.14"
tokio = { version="1.43.0", features = ["full"] }
